# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foucs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
    ]
