# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foucs', '0004_myuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(blank=True, max_length=256, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.CharField(blank=True, max_length=256, verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile',
            field=models.TextField(blank=True, verbose_name='profile'),
        ),
    ]
