# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foucs', '0006_auto_20170810_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='artical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foucs.Artical'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foucs.Comment'),
        ),
    ]
